N3DPS/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About|N3DPS')

@main.route("/medical-am-covid-19")
def covid19():
    return

N3DPS/store/routes.py
from flask import render_template, Blueprint
from flask_login import login_required

store = Blueprint('store',__name__)

@store.route("/redeem")
@login_required
def redeem():
    return render_template('redeem.html', title='Redeem|N3DPS')

@store.route("/donate")
@login_required
def donate():
    return render_template('Donate.html', title='Donate|N3DPS')

N3DPS/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from N3DPS import db, bcrypt
from N3DPS.models import User_sql
from N3DPS.users.forms import (SignupForm, LoginForm, UpdateAccountForm,
                                RequestResetForm, ResetPasswordForm)
from N3DPS.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/signup", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = SignupForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User_sql(fname=form.fname.data, lname=form.lname.data, 
                        username=form.username.data, email=form.email.data, 
                        password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to login', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title='Signup|N3DPS', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User_sql.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.account'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login|N3DPS', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account details have been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.fname.data = current_user.fname
        form.lname.data = current_user.lname
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file =url_for('static', filename='images/profile_pics/' + current_user.image_file)
    return render_template('account.html', title='My Account|N3DPS', 
                            image_file=image_file, form=form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User_sql.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User_sql.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

N3DPS/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>Our Aim</h1>
    <p>
        The aim of the National 3D Printing Society is to connect like minded societies to allow cooperation and help further the field of student 3D printing. We believe 3D printing is a technology that all students should have access to in some form, and we want to help facilitate the starting of more societies around the country.
        The Network aims to aid in sharing knowledge between universities, with the ultimate goal of creating a generation of graduates that have the skills to use rapid prototyping and other related technologies in a realistic and useful way.
        There will be a range of types of society that the Network aims to work with. Whilst many 3D printing related societies will be born out of engineering departments, there is huge scope for student work in architectural, medical, arts and humanitarian fields – to name but a few. The Network embraces this diversity and it would be in the best interest for the collective skills and resources of the Network to try to maximise the breadth of societies involved.
        For students looking to start 3D printing related societies in particular, the Network exists to put you in contact with other students who have had similar experiences to you. We can offer guidance and advice, and help with things like branding and finding projects or sponsors.
        For existing 3D printing related societies, we can connect you with your counterparts in other universities and help raise the profile of your society around the country.
        For existing societies that want to get involved in 3D printing, we can offer technical advice to help you get your plans off the ground.
    </p>
{% endblock content %}

N3DPS/templates/account.html
{% extends "layout.html" %}
{% block content %}
<section>
    <div class="container p-5">
        <div class="row">
          <div class="col-8 col-sm-6 col-lg-6">
            <img src="{{ image_file }}" alt="thumbnail" class="img-thumbnail">
          </div>
          <div class="col-5 col-lg-3">
            <div class="card teal">
                <div class="card-body">
                    <h6 class="font-weight-bold cyan-lighter-hover mb-3">Points Pending</h6>
                </div>
            </div>
          </div>
          <div class="col-5 col-lg-3">
            <div class="card teal">
                <div class="card-body">
                    <h6 class="font-weight-bold cyan-lighter-hover mb-3">Points</h6>
                </div>
            </div>
          </div>
        </div>
        <div class="row p-3">
            <div class="col-9 col-lg-6">
            </div>
            <div class="col-9 col-lg-6">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">My Account Info</legend>
                        <div class="form-group">
                            {{ form.fname.label(class="form-control-label") }}
                            {% if form.fname.errors %}
                                {{ form.fname(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.fname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.fname(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.lname.label(class="form-control-label") }}
        
                            {% if form.lname.errors %}
                                {{ form.lname(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.lname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.lname(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
        
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.picture.label() }}
                            {{ form.picture(class="form-control-file") }}
                            {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-default btn-rounded waves-effect") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

N3DPS/templates/add_product.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section p-5">
    <form method="POST" action="">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Product</legend>
            <div class="form-group">
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

N3DPS/templates/add_stock.html
{% extends "layout.html" %}
{% block content %}
    hi
{% endblock content %}

N3DPS/templates/admin_donate.html
{% extends "layout.html" %}
{% block content %}
    <section>
        <div class="container p-5">
            <div class="col-sm-12 table-responsive">
                <table class="display table table-striped text-center table-bordered table-sm dataTable"
                cellspacing="0" width="100%" role="grid" aria-describedby="dtBasicExample_info" style="width: 100%;">
                    <thead>
                        <th>FDM Number</th>
                        <th>Order Number</th>
                        <th>Username</th>
                        <th>Product</th>
                        <th>Delivery Method</th>
                        <th>Quantity</th>
                        <th>Delivered Quantity</th>
                        <th>Material Used</th>
                        <th>Filament Brand</th>
                        <th>At Igus</th>
                        <th>Amend Order</th>
                    </thead>
                    <tr  role="row" style="background-color: #bbb">
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                        <td>
                            0
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </section>
{% endblock content %}

N3DPS/templates/admin_management.html
{% extends "layout.html" %}
{% block content %}
    hi
{% endblock content %}

N3DPS/templates/admin_panel.html
{% extends "layout.html" %}
{% block content %}
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4"style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="#">Approvals</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="{{ url_for('manage.admin_donate') }}">Donation view</a>
            </div>
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="#">Account Overview</a>
            </div>
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="#">Redeem</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="{{ url_for('manage.manageproduct') }}">Create Product</a>
            </div>
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="#">Admin Overview</a>
            </div>
            <div class="col-md-4" style="text-align:center">
                <a class="btn btn-rounded btn-default btn-lg" href="#">Add stock</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

N3DPS/templates/donate.html
{% extends "layout.html" %}
{% block content %}
<section>
    <div class="container justify-content-center">
        <article style="width: 1000px; border: 2px solid gray;  
              padding: 5px; border-radius: 10px;  
                              margin:5px;"> 
        
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <h2 class="font-weight-bold">Filament</h2>
                            <img src="https://mdbootstrap.com/img/Others/documentation/img%20(75)-mini.jpg" alt="RS Components" height="100">
                        </div>
                        <div class="col-md-4">
                            <h1 class="font-weight-bold">150</h1>
                            <h2 class="font-weight-bold">Cost</h2>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="row">
                        <div class="col-md-7">
                            <p>This is where the description will go.This is where the description will go.This is where the description will go.This is where the description will go.</p>
                        </div>
                        <div class="col-md-5">
                            <button type="button" class="btn btn-outline-success waves-effect align:center">Redeem</button>
                        </div>
                    </div>
                </div>   
            </div>
        </article>
    </div>
</section>
{% endblock content %}

N3DPS/templates/home.html
{% extends "layout.html" %}
{% block content %}
    
    <section>
        <div class="row mx-1">
            <div class="col-md-12 mb-4">
                <div class="card card-image" style="background-image: url('/static/images/latest-design-stacks.png'); background-repeat: no-repeat; background-size: 100%; background-position: center center;">
                    <div class="text-white text-left d-flex align-items-center rgba-black-light py-5 px-4">
                        <div class="p-5">
                            <h1 class="card-title py-3">Supplying the nation with PPE</h1>
                            <p class="pb-3">
                                Please sign up to be added to the N3DPS COVID-19 database. Working with Medical Supply Drive UK, N3DPS has assembled a manufacturing and distribution
                                network to help meet the PPE demand during this national pandemic.
                            </p>
                            <button class="btn btn-rounded btn-outline-white" href="{{ url_for('main.covid19') }}">Find Out More</button>
                            <button class="btn btn-rounded btn-outline-white" href="{{ url_for('users.signup') }}">Sign up</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container ">
        <div class="row">
            <div class="col">
                hello 
            </div>
            <div class="col">
                slack
            </div>
        </div>
    </div>
        
   
{% endblock content %}

N3DPS/templates/layout.html
  
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>N3DPS</title>
    {% endif %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
            <a class="navbar-brand" href="https://national3dprintingsociety.co.uk">
                <img src="static/images/N3DPS-Logo-RT.png" class="d-inline-block align-top" alt="N3DPS" height="60">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
              aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <!-- this is temp -->
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="https://national3dprintingsociety.co.uk">Main Site
                  </a>
                </li>
              </ul>

              <!-- end of temp -->
              <!-- <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Medical AM (COVID-19)
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">About us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">What We Offer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Universities</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Donate</a>
                </li>
              </ul> -->
              <ul class="navbar-nav ml-auto nav-flex-icons">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('store.redeem') }}">Redeem</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('store.donate') }}">Donate</a>
                </li>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.account') }}">
                  <i class="fas fa-user"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
                  {% if current_user.level >= 2 %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('manage.admin') }}">Admin</a>
                    </li>
                  {% endif %}
                {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('users.signup') }}">Signup</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  <a href="https://twitter.com/N3DPS" class="nav-link waves-effect waves-light">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="https://www.facebook.com/N3DPS/" class="nav-link waves-effect waves-light">
                    <i class="fab fa-facebook"></i>
                  </a>
                </li>
                <li class="nav-item">
                    <a href="https://www.instagram.com/n3dps" class="nav-link waves-effect waves-light">
                      <i class="fab fa-instagram"></i>
                    </a>
                </li>
              </ul>
            </div>
          </nav>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}

    <footer class="page-footer font-small">
        <div class="container">
        <div class="footer-copyright row justify-content-center">
            <h2>
                Proudly Supported By
            </h2>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-md-auto">
                <a href="https://intigo3d.com/">
                    <img src="static/images/intigo_n3dps.png" alt="Intigo" height="100">
                </a>
            </div>
            <div class="col-12 col-md-auto">
                <a href="https://3dgbire.pro/">
                    <img src="static/images/3dgbire.jpg" alt="3DGBIRE" height="100">
                </a>
            </div>
            <div class="col-3 col-md-auto">
                <a href="https://projectsbeyondborders.com/">
                    <img src="static/images/pbb_n3dps-1.png" alt="Projects Beyond Borders" height="100">
                </a>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-md-auto">
                <a href="https://www.powerhousehub.com/">
                    <img src="static/images/mediasphere.png" alt="Media Sphere" height="100">
                </a>
            </div>
            <div class="col-12 col-md-auto">
                <a href="https://uk.rs-online.com/">
                    <img src="static/images/rs-components.jpg" alt="RS Components" height="100">
                </a>
            </div>
        </div>
        </div>
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright: National 3D Printing Society
        </div>
    </footer>
</body>
</html>

N3DPS/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

N3DPS/templates/manage_product.html
{% extends "layout.html" %}
{% block content %}
    <section>
        <div class="container p-5">
            <div class="row">
                <div class="col" style="text-align:right">
                    <a class="btn btn-rounded btn-default btn-lg" href="{{ url_for('manage.addproduct') }}">Add stock</a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 table-responsive">
                    <table class="display table table-striped text-center table-bordered table-sm dataTable"
                    cellspacing="0" width="100%" role="grid" aria-describedby="dtBasicExample_info" style="width: 100%;">
                        <thead>
                            <th>Picture</th>
                            <th>Product ID</th>
                            <th>Product Name</th>
                            <th>Discription</th>
                            <th>value</th>
                            <th>Location</th>
                            <th>Edit</th>
                        </thead>
                        <tr role="row" style="background-color: #bbb">
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                0
                            </td>
                            <td>
                                edit button
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}